### ISSUE TITLE
please remove flutter dep

### ISSUE THREAD

**Issue by atomGit** [doug-101/ConvertAll#2]
the overhead due to flutter is outright **obnoxious**, as is the build time

**Comment by doug-101** [comment]
How slow and short on resources is your PC?  You can't do something else for a few minutes while it builds?

For those that prefer it, the old Python-based version of ConvertAll is still available at `doug-101/ConvertAll-py`.  But you'll need to pull it - I don't plan on doing any releases.

By the way, do you often get what you want by using impolite terms like "outright obnoxious" in bold?  Please keep in mind that this is free software, and my time to create and release it is volunteered.  In case there was any doubt, this issue will be closed with a won't fix.

-Doug

**Comment by atomGit** [comment]
it's not just the build time - it's the overhead, as i wrote

multi-GB of space and >50,000 files because of flutter which treated my system like a trash can, dumping garbage all over the damn place

```
~/.cache/flutter-engine - 576 MB, 1,496 files
~/.pub-cache - 149 MB, 10,678 files
~/.rustup - 1.1 GB, 39,489 files
```

sure, it's your s/w and it's free s/w, and maybe i don't respect that enough at times, but that doesn't mean one cannot be critical and this amount of overhead--for a unit converter--is obnoxious IMO
